CHUNK_OVERLAP: 30
CHUNK_SIZE: 300
DATA_PATH: data/
DB_FAISS_PATH: vectorstore/db_faiss
DEVICE: cuda
EMBEDDINGS: sentence-transformers/all-mpnet-base-v2
MAX_NEW_TOKENS: 1048
MODEL_BIN_PATH: models/mistral-7b-instruct-v0.1.Q5_K_M.gguf
MODEL_TYPE: mistral
RETURN_SOURCE_DOCUMENTS: true
TEMPERATURE: 0.0
VECTOR_COUNT: 2
